### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by cdiggins** [magnetar-io/strange_matter#9]
There is a lot of useful information across the site but it is hard to find the most best path through it. For example, one would not know that the "Wiki" has as much useful information as it does. The ReadMe should serve as a landing page with links to the key pieces of information, and have a project summary.  It seems that for the technically minded, the "https://github.com/magnetar-io/strange_matter/wiki/005_Technical_Concepts" is effectively the working specification for now?

**Comment by gschleusner1972** [comment]
https://github.com/magnetar-io/strange_matter/blob/main/README.md  Updated based on Chris's Description.
